version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_COSMOSDB_CONNECTION_STRING=${AZURE_COSMOSDB_CONNECTION_STRING}
    volumes:
      - ./data:/app/data
    restart: unless-stopped