apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: document-qa-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/bigquery-proj-456519/document-qa-system:latest
          resources:
            limits:
              memory: 2Gi
              cpu: '2'
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ANTHROPIC_API_KEY
                  key: latest